version: '3.7'
services:
  user:
    container_name: user-managment
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8000:5000
    volumes:
      - ./:/usr/src/app
    env_file: ./.env
    depends_on:
      - user-database
    networks:
      - users

  user-database:
    container_name: user-database
    image: postgres:15
    restart: always
    ports:
      - 5430:5432
    env_file: ./.env
    volumes:
      - user-database-data:/var/lib/postgresql/data
    networks:
      - users

volumes:
  user-database-data:

networks:
  users: